#!/usr/bin/env node
const {PBFToGeoPackage} = require('./built/index');
const path = require('path');

console.log('PBF to GeoPackage Converter');

const pbfFile = path.resolve(process.cwd(), process.argv[2]);
const geoPackageFile = path.resolve(process.cwd(), process.argv[3]);

console.log('Converting %s to %s', pbfFile, geoPackageFile);
// const temp = new GeoJSONToGeoPackage();
new PBFToGeoPackage().convert({ pbf: pbfFile, geoPackage: geoPackageFile }).then(() => {
  console.log('File conversion complete');
  console.log('Converted %s to %s', pbfFile, geoPackageFile);
});

